### ISSUE TITLE
Issues with metadata / data object interface

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#45]
From our discussion today:

1. `EAbstractData::meta()` should initialize the user meta object if it doesn't exist yet
2. ACE currently overwrites the user meta with a blank object at the end of an analytic run, which undoes any metadata saved by a data object.

**Comment by 4ctrl-alt-del** [comment]
Fixed with commit 45322e52e52043ec24f1ba7d745e0231eb8d25b0

I also temporarily disabled the GUI library in that commit so you should be able to compile and install the whole library. Let me know if this fixes your metadata issues.

**Comment by bentsherman** [comment]
Almost. It doesn't crash anymore but my metadata still isn't saved properly. I think you coded everything right but `EAbstractData::meta()` returns a copy, not a reference, so I can't access the main metadata object.

**Comment by 4ctrl-alt-del** [comment]
The new metadata system no longer works with references. It follows Qt's COW(Copy On Write) methodology. So it works like a QString.

so meta() now returns a copy of the user metadata and setMeta(...) overwrites the entire user metadata of the data object. So now you do something like this:

EMetadata root {meta()};
...
// Manipulate root such as inserting new keys
...
setMeta(root);

Sorry about the confusion perhaps I should be more specific with the comments.

**Comment by bentsherman** [comment]
Ah, that fixes it. Thanks Josh!
